### ISSUE TITLE
Implement DataChannel

### ISSUE THREAD

**Issue by ibc** [versatica/libmediasoupclient#53]
This is, DataProducer and DataConsumer as in mediasoup-client JS lib.

**Comment by tdrz** [comment]
Any ETA on this one?

**Comment by ibc** [comment]
No. But [this](https://mediasoup.org/sponsors/#become-a-sponsor) helps.

**Comment by tdrz** [comment]
Hi guys, are you interested in PRs on this issue? 

I've been making progress implementing this for a PoC of mine. So far I am able to send and receive text messages to/from the mediasoup-demo application using the mediasoup-broadcaster-demo. Haven't tried the binary data yet and it still needs a lot of cleaning up, some tests implementation and the like.

If you are interested in PRs, I could spend more time on it making it better and then create a PR. Otherwise, since for me it's just for a PoC, I won't do it.

Just let me know.

**Comment by jmillan** [comment]
Sure @copiltembel, 

A PR would be very welcome

**Comment by tdrz** [comment]
@jmillan Cool, will hopefully have it ready sometime next week.

**Comment by jmillan** [comment]
Thanks a lot, will happily review it. We are (mediasoup authors) now quite busy these days, so take your time.

**Comment by ibc** [comment]
Can we close this?
